import { ISubjectStorage } from "../utils/types";

export const subjectsStorage: ISubjectStorage[] = [
  {
    id: 1,
    nameSubject: "",
    countByLab: 0,
    RGR: { status: false, mark: 0, maxMark: 20, passed: false },
    CourseWork: { status: false, mark: 0, maxMark: 100, passed: false },
    Presentation: { status: false, mark: 0, maxMark: 20, passed: false },
    Exam: { status: false, mark: 0, maxMark: 0, passed: false },
    ExamCredits: 1,
    CourseWorkCredits: 1,
    score_subj: 0,
    max_score_subj: 0,
  },
  {
    id: 2,
    nameSubject: "",
    countByLab: 0,
    RGR: { status: false, mark: 0, maxMark: 20, passed: false },
    CourseWork: { status: false, mark: 0, maxMark: 100, passed: false },
    Presentation: { status: false, mark: 0, maxMark: 20, passed: false },
    Exam: { status: false, mark: 0, maxMark: 100, passed: false },
    ExamCredits: 1,
    CourseWorkCredits: 1,
    score_subj: 0,
    max_score_subj: 0,
  },
  {
    id: 3,
    nameSubject: "",
    countByLab: 0,
    RGR: { status: false, mark: 0, maxMark: 20, passed: false },
    CourseWork: { status: false, mark: 0, maxMark: 100, passed: false },
    Presentation: { status: false, mark: 0, maxMark: 20, passed: false },
    Exam: { status: false, mark: 0, maxMark: 100, passed: false },
    ExamCredits: 1,
    CourseWorkCredits: 1,
    score_subj: 0,
    max_score_subj: 0,
  },
  {
    id: 4,
    nameSubject: "",
    countByLab: 0,
    RGR: { status: false, mark: 0, maxMark: 20, passed: false },
    CourseWork: { status: false, mark: 0, maxMark: 100, passed: false },
    Presentation: { status: false, mark: 0, maxMark: 20, passed: false },
    Exam: { status: false, mark: 0, maxMark: 100, passed: false },
    ExamCredits: 1,
    CourseWorkCredits: 1,
    score_subj: 0,
    max_score_subj: 0,
  },
  {
    id: 5,
    nameSubject: "",
    countByLab: 0,
    RGR: { status: false, mark: 0, maxMark: 20, passed: false },
    CourseWork: { status: false, mark: 0, maxMark: 100, passed: false },
    Presentation: { status: false, mark: 0, maxMark: 20, passed: false },
    Exam: { status: false, mark: 0, maxMark: 100, passed: false },
    ExamCredits: 1,
    CourseWorkCredits: 1,
    score_subj: 0,
    max_score_subj: 0,
  },
  {
    id: 6,
    nameSubject: "",
    countByLab: 0,
    RGR: { status: false, mark: 0, maxMark: 20, passed: false },
    CourseWork: { status: false, mark: 0, maxMark: 100, passed: false },
    Presentation: { status: false, mark: 0, maxMark: 20, passed: false },
    Exam: { status: false, mark: 0, maxMark: 100, passed: false },
    ExamCredits: 1,
    CourseWorkCredits: 1,
    score_subj: 0,
    max_score_subj: 0,
  },
  {
    id: 7,
    nameSubject: "",
    countByLab: 0,
    RGR: { status: false, mark: 0, maxMark: 20, passed: false },
    CourseWork: { status: false, mark: 0, maxMark: 100, passed: false },
    Presentation: { status: false, mark: 0, maxMark: 20, passed: false },
    Exam: { status: false, mark: 0, maxMark: 100, passed: false },
    ExamCredits: 1,
    CourseWorkCredits: 1,
    score_subj: 0,
    max_score_subj: 0,
  },
  {
    id: 8,
    nameSubject: "",
    countByLab: 0,
    RGR: { status: false, mark: 0, maxMark: 20, passed: false },
    CourseWork: { status: false, mark: 0, maxMark: 100, passed: false },
    Presentation: { status: false, mark: 0, maxMark: 20, passed: false },
    Exam: { status: false, mark: 0, maxMark: 100, passed: false },
    ExamCredits: 1,
    CourseWorkCredits: 1,
    score_subj: 0,
    max_score_subj: 0,
  },
  {
    id: 9,
    nameSubject: "",
    countByLab: 0,
    RGR: { status: false, mark: 0, maxMark: 20, passed: false },
    CourseWork: { status: false, mark: 0, maxMark: 100, passed: false },
    Presentation: { status: false, mark: 0, maxMark: 20, passed: false },
    Exam: { status: false, mark: 0, maxMark: 100, passed: false },
    ExamCredits: 1,
    CourseWorkCredits: 1,
    score_subj: 0,
    max_score_subj: 0,
  },
  {
    id: 10,
    nameSubject: "",
    countByLab: 0,
    RGR: { status: false, mark: 0, maxMark: 20, passed: false },
    CourseWork: { status: false, mark: 0, maxMark: 100, passed: false },
    Presentation: { status: false, mark: 0, maxMark: 20, passed: false },
    Exam: { status: false, mark: 0, maxMark: 100, passed: false },
    ExamCredits: 1,
    CourseWorkCredits: 1,
    score_subj: 0,
    max_score_subj: 0,
  },
];
